### PR TITLE
Upgrade dependencies

### LINKED ISSUE #2: ftp can show only 100 files
FTP always shows 100 files, although I have more of them.

### PR DESCRIPTION
**Pull request by Gee19**
- FtpServer added support for paging and increased pagesize to 1000

Fixes #2

### CODE REVIEW

**Comment by Aida-Enna** [comment]
Oooh, good stuff. Thank you!

**Comment by Gee19** [comment]
Could you put up another release for the folks who don't have VS?

:)

**Comment by Aida-Enna** [comment]
Yep, I'll take care of it when I get home.

**Comment by Aida-Enna** [comment]
Yep, I'll take care of it :)

**Pull request merged**
